//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsShakingNZ.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhatsShakingNZ.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the app.
        /// </summary>
        public static string AboutPageAboutAppHeading {
            get {
                return ResourceManager.GetString("AboutPageAboutAppHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s Shaking NZ? uses the Geonet.org.nz data feed to provide you with up to date information about the latest earthquakes around New Zealand.
        ///Please tweet or email us with any problems you find or suggestions for features you&apos;d like to see in the next version.
        ///.
        /// </summary>
        public static string AboutPageAboutAppText {
            get {
                return ResourceManager.GetString("AboutPageAboutAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update 1.1.
        /// </summary>
        public static string AboutPageUpdate11Heading {
            get {
                return ResourceManager.GetString("AboutPageUpdate11Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed an issue where sometimes the application would crash when the settings page was accessed too quickly.
        ///Modified the magnitude and depth values to display with the correct number of decimal places, as specified on the Geonet website.
        ///.
        /// </summary>
        public static string AboutPageUpdate11Text {
            get {
                return ResourceManager.GetString("AboutPageUpdate11Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update 1.2.
        /// </summary>
        public static string AboutPageUpdate12Heading {
            get {
                return ResourceManager.GetString("AboutPageUpdate12Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geonet have recently changed the way they provide their data feed, and we can now only retrieve the latest 30 quakes. Previously we could retrieve the latest N days of quakes - this was limited to a maximum of 3 days within the app. However, quakes are now reported on significantly faster.
        ///Now you can specify the maximum number of quakes you would like displayed - from 10 to 30. In some cases you may get less than your specified maximum, if your &quot;minimum magnitude to display&quot; value is set high enough.
        ///Mod [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutPageUpdate12Text {
            get {
                return ResourceManager.GetString("AboutPageUpdate12Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update 1.3.
        /// </summary>
        public static string AboutPageUpdate13Heading {
            get {
                return ResourceManager.GetString("AboutPageUpdate13Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now see whether an earthquake has been reviewed by a Geonet technician or is automatically reported.
        ///The list view now shows earthquake location as a direction and distance from the nearest town or city.
        ///Added an option to see all of the latest recorded earthquakes from around the country, rather than just the latest earthquakes likely to have been felt by people. This can give you an idea of just how many minor earthquakes happen around New Zealand every day. Note that this is still restricted to [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutPageUpdate13Text {
            get {
                return ResourceManager.GetString("AboutPageUpdate13Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAboutMenuItemText {
            get {
                return ResourceManager.GetString("AppBarAboutMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list view.
        /// </summary>
        public static string AppBarListViewButtonText {
            get {
                return ResourceManager.GetString("AppBarListViewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map view.
        /// </summary>
        public static string AppBarMapViewButtonText {
            get {
                return ResourceManager.GetString("AppBarMapViewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefreshButtonText {
            get {
                return ResourceManager.GetString("AppBarRefreshButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettingsMenuItemText {
            get {
                return ResourceManager.GetString("AppBarSettingsMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom in.
        /// </summary>
        public static string AppBarZoomInButtonText {
            get {
                return ResourceManager.GetString("AppBarZoomInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom out.
        /// </summary>
        public static string AppBarZoomOutButtonText {
            get {
                return ResourceManager.GetString("AppBarZoomOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT&apos;S SHAKING NZ?.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no quakes available that fit the criteria for your settings. Try lowering the minimum display values..
        /// </summary>
        public static string BasePageRestrictiveSettingsToastMessage {
            get {
                return ResourceManager.GetString("BasePageRestrictiveSettingsToastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictive Settings.
        /// </summary>
        public static string BasePageRestrictiveSettingsToastTitle {
            get {
                return ResourceManager.GetString("BasePageRestrictiveSettingsToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth: {0} kilometers.
        /// </summary>
        public static string ConverterLongDepthFormat {
            get {
                return ResourceManager.GetString("ConverterLongDepthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} km.
        /// </summary>
        public static string ConverterShortDepthFormat {
            get {
                return ResourceManager.GetString("ConverterShortDepthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} km {1} of {2}.
        /// </summary>
        public static string EarthquakeLocationFormat {
            get {
                return ResourceManager.GetString("EarthquakeLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An automatic earthquake location that has not been reviewed by a duty officer or analyst..
        /// </summary>
        public static string EarthquakeStatusAutomatic {
            get {
                return ResourceManager.GetString("EarthquakeStatusAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! This was not a real earthquake and has been deleted..
        /// </summary>
        public static string EarthquakeStatusDeleted {
            get {
                return ResourceManager.GetString("EarthquakeStatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This earthquake location is a duplicate of another one..
        /// </summary>
        public static string EarthquakeStatusDuplicate {
            get {
                return ResourceManager.GetString("EarthquakeStatusDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This earthquake has been reviewed and confirmed by a duty officer or analyst..
        /// </summary>
        public static string EarthquakeStatusReviewed {
            get {
                return ResourceManager.GetString("EarthquakeStatusReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t know what this status means! :(.
        /// </summary>
        public static string EarthquakeStatusUnknown {
            get {
                return ResourceManager.GetString("EarthquakeStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to east.
        /// </summary>
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabling the &quot;all quakes&quot; option will show many more earthquakes than normal, including a large number not felt by people..
        /// </summary>
        public static string GeonetAllQuakesEndpointSettingEnabledWarningToastMessage {
            get {
                return ResourceManager.GetString("GeonetAllQuakesEndpointSettingEnabledWarningToastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning.
        /// </summary>
        public static string GeonetAllQuakesEndpointSettingEnabledWarningToastTitle {
            get {
                return ResourceManager.GetString("GeonetAllQuakesEndpointSettingEnabledWarningToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data received from Geonet was unusable. Please try again..
        /// </summary>
        public static string GeonetProblemBadGeonetData {
            get {
                return ResourceManager.GetString("GeonetProblemBadGeonetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected problem downloading data from Geonet. Please try again..
        /// </summary>
        public static string GeonetProblemDefault {
            get {
                return ResourceManager.GetString("GeonetProblemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with your internet connection. Please check you have connection and then try again..
        /// </summary>
        public static string GeonetProblemNetworkFailure {
            get {
                return ResourceManager.GetString("GeonetProblemNetworkFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geonet sent no data. Please try again..
        /// </summary>
        public static string GeonetProblemNoGeonetData {
            get {
                return ResourceManager.GetString("GeonetProblemNoGeonetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem downloading latest quakes.
        /// </summary>
        public static string GeonetProblemToastTitle {
            get {
                return ResourceManager.GetString("GeonetProblemToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Report.
        /// </summary>
        public static string LittleWatsonMessageBoxCaption {
            get {
                return ResourceManager.GetString("LittleWatsonMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred the last time you ran this application. Would you like to send an email to report it?.
        /// </summary>
        public static string LittleWatsonMessageBoxText {
            get {
                return ResourceManager.GetString("LittleWatsonMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest quake
        ///{0} mag
        ///{1} k deep.
        /// </summary>
        public static string LiveTileBackContentFormat {
            get {
                return ResourceManager.GetString("LiveTileBackContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No quakes in the last 24 hours!.
        /// </summary>
        public static string LiveTileBackContentNoQuakes {
            get {
                return ResourceManager.GetString("LiveTileBackContentNoQuakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest NZ Quakes.
        /// </summary>
        public static string LiveTileDefaultTitle {
            get {
                return ResourceManager.GetString("LiveTileDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in last 24hrs.
        /// </summary>
        public static string LiveTileQuakeCountFormat {
            get {
                return ResourceManager.GetString("LiveTileQuakeCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s Shaking NZ task for live tile.
        /// </summary>
        public static string LiveTileTaskDescription {
            get {
                return ResourceManager.GetString("LiveTileTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scheduled task limit has been reached. please disable other apps scheduled tasks in phone settings..
        /// </summary>
        public static string LiveTileTaskLimitReachedToastMessage {
            get {
                return ResourceManager.GetString("LiveTileTaskLimitReachedToastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot use live tile.
        /// </summary>
        public static string LiveTileTaskLimitReachedToastTitle {
            get {
                return ResourceManager.GetString("LiveTileTaskLimitReachedToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north.
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-{1}.
        /// </summary>
        public static string NorthEastFormat {
            get {
                return ResourceManager.GetString("NorthEastFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest quakes.
        /// </summary>
        public static string PageTitleLatestQuakes {
            get {
                return ResourceManager.GetString("PageTitleLatestQuakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to depth.
        /// </summary>
        public static string QuakeDisplayPageDepthHeading {
            get {
                return ResourceManager.GetString("QuakeDisplayPageDepthHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magnitude.
        /// </summary>
        public static string QuakeDisplayPageMagnitudeHeading {
            get {
                return ResourceManager.GetString("QuakeDisplayPageMagnitudeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string QuakeDisplayPageStatusHeading {
            get {
                return ResourceManager.GetString("QuakeDisplayPageStatusHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string QuakeDisplayPageTimeHeading {
            get {
                return ResourceManager.GetString("QuakeDisplayPageTimeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum number of quakes to show.
        /// </summary>
        public static string SettingsPageMaximumQuakesToShowHeading {
            get {
                return ResourceManager.GetString("SettingsPageMaximumQuakesToShowHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum magnitude to display.
        /// </summary>
        public static string SettingsPageMinimumDisplayMagnitudeHeading {
            get {
                return ResourceManager.GetString("SettingsPageMinimumDisplayMagnitudeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum magnitude to highlight.
        /// </summary>
        public static string SettingsPageMinimumHighlightMagnitudeHeading {
            get {
                return ResourceManager.GetString("SettingsPageMinimumHighlightMagnitudeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use 24 hour clock.
        /// </summary>
        public static string SettingsPageUse24HourClockHeading {
            get {
                return ResourceManager.GetString("SettingsPageUse24HourClockHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all earthquakes (not just those felt).
        /// </summary>
        public static string SettingsPageUseGeonetAllQuakesEndpointHeading {
            get {
                return ResourceManager.GetString("SettingsPageUseGeonetAllQuakesEndpointHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to live tile.
        /// </summary>
        public static string SettingsPageUseLiveTileHeading {
            get {
                return ResourceManager.GetString("SettingsPageUseLiveTileHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to west.
        /// </summary>
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
    }
}
