//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsShakingNZ.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhatsShakingNZ.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAboutMenuItemText {
            get {
                return ResourceManager.GetString("AppBarAboutMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list view.
        /// </summary>
        public static string AppBarListViewButtonText {
            get {
                return ResourceManager.GetString("AppBarListViewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map view.
        /// </summary>
        public static string AppBarMapViewButtonText {
            get {
                return ResourceManager.GetString("AppBarMapViewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefreshButtonText {
            get {
                return ResourceManager.GetString("AppBarRefreshButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettingsMenuItemText {
            get {
                return ResourceManager.GetString("AppBarSettingsMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom in.
        /// </summary>
        public static string AppBarZoomInButtonText {
            get {
                return ResourceManager.GetString("AppBarZoomInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom out.
        /// </summary>
        public static string AppBarZoomOutButtonText {
            get {
                return ResourceManager.GetString("AppBarZoomOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please check your data connection is working.
        /// </summary>
        public static string BasePageNoConnectivityToastMessage {
            get {
                return ResourceManager.GetString("BasePageNoConnectivityToastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to problem retrieving quakes.
        /// </summary>
        public static string BasePageNoConnectivityToastTitle {
            get {
                return ResourceManager.GetString("BasePageNoConnectivityToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An automatic earthquake location that has not been reviewed by a duty officer or analyst..
        /// </summary>
        public static string EarthquakeStatusAutomatic {
            get {
                return ResourceManager.GetString("EarthquakeStatusAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! This was not a real earthquake and has been deleted..
        /// </summary>
        public static string EarthquakeStatusDeleted {
            get {
                return ResourceManager.GetString("EarthquakeStatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This earthquake location is a duplicate of another one..
        /// </summary>
        public static string EarthquakeStatusDuplicate {
            get {
                return ResourceManager.GetString("EarthquakeStatusDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This earthquake has been reviewed and confirmed by a duty officer or analyst..
        /// </summary>
        public static string EarthquakeStatusReviewed {
            get {
                return ResourceManager.GetString("EarthquakeStatusReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t know what this status means! :(.
        /// </summary>
        public static string EarthquakeStatusUnknown {
            get {
                return ResourceManager.GetString("EarthquakeStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Report.
        /// </summary>
        public static string LittleWatsonMessageBoxCaption {
            get {
                return ResourceManager.GetString("LittleWatsonMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred the last time you ran this application. Would you like to send an email to report it?.
        /// </summary>
        public static string LittleWatsonMessageBoxText {
            get {
                return ResourceManager.GetString("LittleWatsonMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s Shaking NZ task for live tile.
        /// </summary>
        public static string LiveTileTaskDescription {
            get {
                return ResourceManager.GetString("LiveTileTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scheduled task limit has been reached. please disable other apps scheduled tasks in phone settings..
        /// </summary>
        public static string LiveTileTaskLimitReachedToastMessage {
            get {
                return ResourceManager.GetString("LiveTileTaskLimitReachedToastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot use live tile.
        /// </summary>
        public static string LiveTileTaskLimitReachedToastTitle {
            get {
                return ResourceManager.GetString("LiveTileTaskLimitReachedToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest quakes.
        /// </summary>
        public static string PageTitleLatestQuakes {
            get {
                return ResourceManager.GetString("PageTitleLatestQuakes", resourceCulture);
            }
        }
    }
}
